mvc_blog_homepage:
    path:     /
    defaults: { _controller: MvcBlogBundle:Blog:index }

mvc_blog_by_category:
    path:     /blog/category/{slug}
    defaults: { _controller: MvcBlogBundle:Blog:getPostByCategory }
    requirements:
        slug: '[a-zA-Z0-9\-]+'

mvc_blog_show:
    path:     /blog/{slug}
    defaults: { _controller: MvcBlogBundle:Blog:show }
    requirements:
        slug: '[a-zA-Z0-9\-]+'
