language: php

php:
    - 5.6

env:
    - SYMFONY_VERSION=2.6.*

before_script:
    - mysql -e "create database test;"
    - mysql -e "set global wait_timeout=600"
    - composer self-update
    - composer install --dev
    - php app/console doctrine:database:create --env=test
    - php app/console doctrine:schema:create --env=test
    - php app/console doctrine:fixtures:load -n --env=test


after_script:
    - php app/console --env=test doctrine:database:drop --force

script:
    - phpunit -c app