language: php

php:
    - 5.6

env:
    - SYMFONY_VERSION=2.6.*

before_script:
    - mysql -e "create database test;"
    - mysql -e "set global wait_timeout=600"
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION}
    - composer install --dev
    - php app/console --env=test doctrine:schema:create
    - php app/console --env=test doctrine:schema:update --force


after_script:
    - php app/console --env=test doctrine:database:drop --force

script:
    - phpunit